name: NPM Publish

on:
  release:
    types:
      - published
      - prereleased
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-snapshot.[0-9]+'

permissions:
  contents: read
  id-token: write # For provenance

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache

      - name: Install dependencies
        run: npm ci --omit=dev

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: Publish to NPM
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
