name: NPM Publish

on:
  release:
    types:
      - published
      - prereleased
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-snapshot.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use get-npm-cache Action
        uses: ./.github/actions/npm-cache
      - run: npm ci

      - run: npm run test
      - run: npm run build

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
